modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="shadow_of_the_ice"
version="1.0.0"
displayName="Shadow Of The Ice"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="gambi, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.shadow_of_the_ice]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration